services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dap001_todo_webapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_DEBUG=$DJANGO_DEBUG
