# Generated by Django 5.2.7 on 2025-10-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
